version: "3.8"

services:
  zk-prover:
    build:
      context: ./zk-prover
    ports:
      - "3001:3001"
    networks:
      - lightnode

  cli-light-node:
    build:
      context: ./cli-light-node
    depends_on:
      - zk-prover
    environment:
      - GRPC_URL=${GRPC_URL}
      - CONTRACT_ADDR=${CONTRACT_ADDR}
      - ZK_PROVER_URL=${ZK_PROVER_URL}
      - API_REQUEST_TIMEOUT=${API_REQUEST_TIMEOUT}
      - POINTS_API=${POINTS_API}
      - PRIVATE_KEY=${PRIVATE_KEY}
    networks:
      - lightnode

networks:
  lightnode:
    driver: bridge
